# Generated by Django 3.2 on 2025-06-06 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('rent', models.FloatField()),
                ('emi', models.FloatField()),
                ('tax', models.FloatField()),
                ('expence', models.FloatField()),
            ],
        ),
    ]
