# Generated by Django 3.2 on 2025-06-10 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_expence_data_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='expense_monthly',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='data',
            name='income_monthly',
            field=models.FloatField(default=0),
        ),
    ]
