# Generated by Django 3.2 on 2025-06-10 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20250610_1228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='expense_monthly',
        ),
        migrations.RemoveField(
            model_name='data',
            name='income_monthly',
        ),
    ]
