# Generated by Django 3.2 on 2025-06-10 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20250610_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='expense_monthly',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='data',
            name='income_monthly',
            field=models.FloatField(default=0),
        ),
    ]
